### ISSUE TITLE
Missing event

### ISSUE THREAD

**Issue by chapperton** [Greco1899/scrape_ufc_stats#11]
Hi,

It looks like UFC Fight Night: Ortega vs Rodriguez on July 16, 2022 is not pulling in the data? Neither is UFC 280.

Otherwise, everything is awesome.

**Comment by Greco1899** [comment]
Hi @chapperton. Thanks for bringing this up and sorry for the delayed response.

'UFC Fight Night: Ortega vs. Rodriguez' was scrapped and added to `ufc_event_details.csv`, and the script checks this file for missing events before scraping other details, like fight details etc.

I suspect there was some delay between the updating of the event vs the fight details on the UFC website, hence only the event was scrapped. Will spend some time taking a look and populate the missing event.

**Comment by Greco1899** [comment]
@chapperton, added the missing data points. :)

Note to self to add another logic check to compare events across all the files instead of just `ufc_event_details.csv`.

**Comment by chapperton** [comment]
Awesome. It's a great tool. Thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chapperton** [comment]
Hello again,

Looks like the same kind of timing error with the Holloway/Zombie event that took place in Singapore.

The "ufc_fight_stats" script didn't pick up anything for that event.

Just thought you might like to know.

Thanks,
Cameron

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
