### ISSUE TITLE
Fight Details (By Round Totals)

### ISSUE THREAD

**Issue by VictorHolman** [Greco1899/scrape_ufc_stats#2]
Hi. Great work on your scraper. I was wondering if there is a way to scrape the By Round data (totals by round and significant strikes by round). It's available on the fight details page hidden under a drop down (http://ufcstats.com/fight-details/XXXXXXX). If you can think of a way, please let me know (email is victor.holman@gmail.com).

Thanks
<img width="616" alt="Totals By Round" src="https://user-images.githubusercontent.com/112986092/188748244-a8f96cea-e8a3-4dfd-8834-f98d56826f58.PNG">
<img width="597" alt="Significant Strikes By Round" src="https://user-images.githubusercontent.com/112986092/188748261-c7cef9c4-67d2-40af-9161-e94988c8b561.PNG">

**Comment by Greco1899** [comment]
Hi @VictorHolman, thanks for the kind words.

Is this the data that you're looking for?
![EXCEL_2022-09-07_21-53-20](https://user-images.githubusercontent.com/28339294/188896204-60160c3f-44f4-46c1-910a-c52a4e42a8d8.png)

The full data file can be found in here [ufc_fight_results.csv](https://github.com/Greco1899/scrape_ufc_stats/blob/main/ufc_fight_results.csv).
The corresponding code is [here](https://github.com/Greco1899/scrape_ufc_stats/blob/bd78a46e12ec4e16be9e4f081b956d7bf6da3ad8/scrape_ufc_stats_library.py#L95).

**Comment by VictorHolman** [comment]
Yes! Man, you’re awesome. Again, you’re code/scrapes are very clean.

Thank you!

**Comment by Greco1899** [comment]
You're welcome, enjoy!
