### ISSUE TITLE
Scraping UFC data reflecting fighter stats as they were just before the fight took place

### ISSUE THREAD

**Issue by apavlo89** [Greco1899/scrape_ufc_stats#8]
Dear Greco1899,

Awesome scraper, however I am trying to update the dataset from https://www.kaggle.com/datasets/mdabbert/ultimate-ufc-dataset and unfortunately while your scraper would help me fill in a lot of the data needed, there are several fighter statistics that your scraper doesn't acquire such as some in this list of variables I am trying to download:

R_fighter	B_fighter	R_odds	B_odds	R_ev	B_ev	date	fight_night	location	country	Winner	title_bout	weight_class	gender	no_of_rounds	B_current_lose_streak	B_current_win_streak	B_draw	B_avg_SIG_STR_landed	B_avg_SIG_STR_pct	B_avg_SUB_ATT	B_avg_TD_landed	B_avg_TD_pct	B_longest_win_streak	B_losses	B_total_rounds_fought	B_total_title_bouts	B_win_by_Decision_Majority	B_win_by_Decision_Split	B_win_by_Decision_Unanimous	B_win_by_KO/TKO	B_win_by_Submission	B_win_by_TKO_Doctor_Stoppage	B_wins	B_Stance	B_Height_cms	B_Reach_cms	B_Weight_lbs	R_current_lose_streak	R_current_win_streak	R_draw	R_avg_SIG_STR_landed	R_avg_SIG_STR_pct	R_avg_SUB_ATT	R_avg_TD_landed	R_avg_TD_pct	R_longest_win_streak	R_losses	R_total_rounds_fought	R_total_title_bouts	R_win_by_Decision_Majority	R_win_by_Decision_Split	R_win_by_Decision_Unanimous	R_win_by_KO/TKO	R_win_by_Submission	R_win_by_TKO_Doctor_Stoppage	R_wins	R_Stance	R_Height_cms	R_Reach_cms	R_Weight_lbs	R_age	B_age

Do you have any awareness of such code to do this? The data also need to be adjusted so that for each row the fighter statistics reflect their stats before the fight took placeIf not would it be something you are interested in?

**Comment by Greco1899** [comment]
Hi @apavlo89. Thanks, I'm glad that it is helpful.

However, I'm not aware of other code repos that could fill your requirements. This is not something that I am looking to work on at the moment either.
